# Generated by Django 6.0.3 on 2026-03-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_utilisateur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='derniere_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='official_homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
