# Generated by Django 6.0.3 on 2026-03-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='Categorie',
            new_name='categorie',
        ),
        migrations.AddField(
            model_name='annonce',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('VENDU', 'Vendu'), ('EXPIRÉ', 'Expiré'), ('RÉSERVÉ', 'Réservé')], default='DISPONIBLE', max_length=30),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='prix',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
