# Generated by Django 6.0.3 on 2026-03-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_rename_categorie_annonce_categorie_annonce_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
