# Generated by Django 6.0.3 on 2026-03-31 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_recherche'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrixMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('prix_moyen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_minimum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_maximum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_calcul', models.DateField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_marche', to='annonces.categorie')),
            ],
        ),
    ]
