# Generated by Django 6.0.3 on 2026-03-31 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_prixmarche'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('url_miniature', models.URLField(blank=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('mise_a_jour', models.DateTimeField(auto_now=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annonces.annonce')),
            ],
        ),
    ]
