# Generated by Django 6.0.3 on 2026-03-31 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_type', models.CharField(choices=[('ANNONCE', 'Annonce'), ('UTILISATEUR', 'Utilisateur'), ('MESSAGE', 'Message')], max_length=20)),
                ('objet_signale_id', models.IntegerField()),
                ('raison', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RESOLU', 'Résolu'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('note_resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_resolus', to=settings.AUTH_USER_MODEL)),
                ('signaleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
